### ISSUE TITLE
Can't run Wildfly image on openshift

### ISSUE THREAD

**Issue by rmpestano** [AdamBien/docklands#15]
Openshift v3 accepts a docker image from docker hub ([see example here](https://blog.openshift.com/deploying-images-from-dockerhub/)) but when I use "airhacks/wildfly" I got the following error when the container starts on openshift:

```

=========================================================================
--
  |  
  | JBoss Bootstrap Environment
  |  
  | JBOSS_HOME: /opt/wildfly-10.1.0.Final
  |  
  | JAVA: /usr/lib/jvm/java-1.8.0/bin/java
  |  
  | JAVA_OPTS:  -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true
  |  
  | =========================================================================
  |  
  | java.lang.IllegalArgumentException: Failed to instantiate class "org.jboss.logmanager.handlers.PeriodicRotatingFileHandler" for handler "FILE"
  | at org.jboss.logmanager.config.AbstractPropertyConfiguration$ConstructAction.validate(AbstractPropertyConfiguration.java:116)
  | at org.jboss.logmanager.config.LogContextConfigurationImpl.doPrepare(LogContextConfigurationImpl.java:335)
  | at org.jboss.logmanager.config.LogContextConfigurationImpl.prepare(LogContextConfigurationImpl.java:288)
  | at org.jboss.logmanager.config.LogContextConfigurationImpl.commit(LogContextConfigurationImpl.java:297)
  | at org.jboss.logmanager.PropertyConfigurator.configure(PropertyConfigurator.java:546)
  | at org.jboss.logmanager.PropertyConfigurator.configure(PropertyConfigurator.java:97)
  | at org.jboss.logmanager.LogManager.readConfiguration(LogManager.java:514)
  | at org.jboss.logmanager.LogManager.readConfiguration(LogManager.java:476)
  | at java.util.logging.LogManager$3.run(LogManager.java:399)
  | at java.util.logging.LogManager$3.run(LogManager.java:396)
  | at java.security.AccessController.doPrivileged(Native Method)
  | at java.util.logging.LogManager.readPrimordialConfiguration(LogManager.java:396)
  | at java.util.logging.LogManager.access$800(LogManager.java:145)
  | at java.util.logging.LogManager$2.run(LogManager.java:345)
  | at java.security.AccessController.doPrivileged(Native Method)
  | at java.util.logging.LogManager.ensureLogManagerInitialized(LogManager.java:338)
  | at java.util.logging.LogManager.getLogManager(LogManager.java:378)
  | at org.jboss.modules.Main.main(Main.java:480)
  | Caused by: java.lang.reflect.InvocationTargetException
  | at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  | at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  | at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  | at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  | at org.jboss.logmanager.config.AbstractPropertyConfiguration$ConstructAction.validate(AbstractPropertyConfiguration.java:114)
  | ... 17 more
  | Caused by: java.io.FileNotFoundException: /opt/wildfly-10.1.0.Final/standalone/log/server.log (No such file or directory)
  | at java.io.FileOutputStream.open0(Native Method)
  | at java.io.FileOutputStream.open(FileOutputStream.java:270)
  | at java.io.FileOutputStream.<init>(FileOutputStream.java:213)

```
I've made a fast research and found this issue on official wildfly image repository:

https://github.com/jboss-dockerfiles/wildfly/issues/25

**Comment by AdamBien** [comment]
Had similar issues with payara -> will test it on openshift. Thanks!
